FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Install ping
RUN export ASPNETCORE_ENVIRONMENT=Beta

FROM base AS final
WORKDIR /app
COPY ./output/ /app/publish/ 
COPY ./appsettings.json /app/
COPY ./appsettings.json /app/publish/
ENTRYPOINT ["dotnet", "/app/publish/EdwardSFlores.Service.dll"]
