version: "3.7"
services:  
  web:
    build: 
      context: "."
      dockerfile: "Dockerfile"
   
    #restart: always
    ports:
      - "15009:80"
      - "15008:443"
    
    container_name: "edwardflores-service-beta"
    # Add network to reach mysql server im host 
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
      
    




      