# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'beta'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: '14'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sh ./build-app.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release.zip
          asset_name: release.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: edwardsflores.com
          username: ${{ secrets.edwardsflores_login }}
          password: ${{ secrets.edwardsflores_password }}
          port: 22
          source: "./release.zip"
          target: "./"
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: edwardsflores.com
          username: ${{ secrets.edwardsflores_login }}
          password: ${{ secrets.edwardsflores_password }}
          port: 22
          script: |
            whoami
            unzip -qq -o release.zip
            cd edwardsflores.com
            cd dist
            cd edward-sflores.com
            \cp ./* -rf ../../../httpdocs/


